# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - 3.2
  - 3.3
  - 3.4
  - oldrel
  - release

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagick++-dev

r_packages:
  - covr
  - rvest
  - devtools
  - pkgdown

after_success:
  - travis_wait 60 test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov(quiet = FALSE)'

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING = "release"
